### ISSUE TITLE
Replace removed text.

### ISSUE THREAD

**Issue by lliss** [azavea/pwd-waterworks-revealed#106]
Replace the text/quotes that were accidentally removed from the version we demoed

**Comment by caseypt** [comment]
Can you reference the removed text? I took a look through the commits, and couldn't find anything.

**Comment by mmcfarland** [comment]
This was from the original document that Victoria sent.  There was a paragraph size quote the was meant to be shown in the beginning of each zone, we simply left it out.

**Comment by lliss** [comment]
In the new design where is this supposed to go? @jfrankl ?

**Comment by jfrankl** [comment]
I don't think there's a great place for it. I'd say put it before the alignment screens—first thing you see when you enter a quest.

Open to other locations.

**Comment by lliss** [comment]
@jfrankl, seems like it might get pretty crowded. Let's have a 5 min chat with @mmcfarland.

**Comment by lliss** [comment]
Making this block of text the last slide in the deck as per discussion.
