### ISSUE TITLE
Restrict when photos can appear for a zone

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#108]
After completing a photo series in a zone, you should not be able to re-activate the photos until you've exited and re-entered the zone.  This prevents the photos from popping up if you linger in a zone after completion.

**Comment by lliss** [comment]
@mmcfarland, this behaviour doesn't seem to happen via location information. Users can tap the target to reactivate the slides but staying in the zone doesn't seem to trigger anything. I'm not sure what changes are necessary here.

**Comment by mmcfarland** [comment]
The behavior we were seeing was that if you're in a zone, complete it and walk around in it, it pops up the photos again.

**Comment by lliss** [comment]
I can't reproduce this in the simulator.

**Comment by lliss** [comment]
Talking about this with @caseypt, we came upon a possible cause of this behaviour. We know that the accuracy of the GPS on the devices is not great. (Expect maybe a meter). Which means if we're near the edge of a zone, the single from the GPS might be bouncing between a point outside the zone and inside. This means that we'd effectively look to the application as though we're jumping in and out of the zone and it would open the zone images. We'll have to test this on some hardware but I have a strong suspicion that this is the cause of the issue as it explains the behaviour and the fact that it can't be reproduced on the simulator.

The easy solution to this might be to add an exit buffer which would be a circle on the zone with a buffer of 1-1.5 meters. To leave a zone we could check to ensure you've left both the zone and the zone buffer.
