### ISSUE TITLE
Move initial orientation instructions to non-caption area 

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#123]
The instructions that tell the user to look for the photo needs to be moved out of the caption area and restyled.

**Comment by jfrankl** [comment]
Here is a set of mockups to show how the orientation instructions should work.

Screen 1: The user would see this only the first time they enter a quest.
![image](https://cloud.githubusercontent.com/assets/1809908/8748561/5616fc4c-2c69-11e5-87bf-d27bbb83cd40.png)

Screen 2: The user will always see this screen when entering a quest.
![image](https://cloud.githubusercontent.com/assets/1809908/8748584/78dc2b76-2c69-11e5-86ae-41f5807ea6fc.png)

Screen 3: The user is now in the quest story mode where they can swipe to continue. All of the captions should be replaced with "Swipe left to continue" text.
![image](https://cloud.githubusercontent.com/assets/1809908/8748603/96aa90f2-2c69-11e5-8933-d78530a2f380.png)
