### ISSUE TITLE
Provision test device

### ISSUE THREAD

**Issue by lliss** [azavea/pwd-waterworks-revealed#136]
Prepare test device for use in field testing.

**Comment by lliss** [comment]
Need device info.

**Comment by arobbi7** [comment]
Additional iPad UDID provided by Victoria: d75412fbee25c68145b1d00bba7a33230975d2d2

**Comment by arobbi7** [comment]
new UDID from Victoria: d75412fbee25c68145b1d00bba7a33230975d2d2

**Comment by arobbi7** [comment]
Device was provisioned on 10.1 and app is operating correctly on device.
