### ISSUE TITLE
Small zone location adjustments

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#146]
Decipher this scavenger hunt of non meaningful spatial adjustments to specific zones:

* Rez zone 2 closer to edge
* New mill deck, split with rez 2
* Above the swimming pool should be back in the corner
* Pier moves in
* Cliff path moves interior
* Flyover moves to bend in path
* Rustic cabin centered on path, move back
* Move bridge closer to path
* Forbey new mill, outer path flat zone

Requires special decoder ring (not provided).

**Comment by arobbi7** [comment]
![wwr screenshot labeled zones](https://cloud.githubusercontent.com/assets/12868342/9741845/c376cf0c-562a-11e5-97ec-d589047b4900.png)

**Comment by arobbi7** [comment]
Move K closer to bridge
H and K should be next to each other on the bridge (though not overlapping)
X should be back in the corner (move towards the pier)
RII moves away from water, onto middle of pier
D moves to bend in path (up on map)
A centered on path, move back a bit (towards top of map)
Move F to be more on the path
E: center on path, move up towards right angle bend
