### ISSUE TITLE
Provide screenshot of map with zone name labels applied

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#147]
The zones will get renamed, as many of them repeat in the `zone.json` files.  Take a screenshot of the [altered zones](https://github.com/azavea/pwd-waterworks-revealed/issues/146) and apply a name/letter label (from the source doc/quest src) to ID them and send to Victoria.

**Comment by mmcfarland** [comment]
A mapping of letter designations to current zone titles:

```
./a/zone.json:    "title": "Rustic Pavilion",
./i/zone.json:    "title": "Deck",
./o/zone.json:    "title": "Reservoir",
./k/zone.json:    "title": "Reservoir",
./f/zone.json:    "title": "Forebay Bridge",
./n/zone.json:    "title": "Cliff Side Path",
./r1/zone.json:    "title": "Decks",
./r2/zone.json:    "title": "Decks",
./l/zone.json:    "title": "Deck of Old Mill House",
./e/zone.json:    "title": "Forebay & New Mill House",
./j/zone.json:    "title": "Reservoir",
./d/zone.json:    "title": "Old Mill House & Forebay",
./h/zone.json:    "title": "New Mill House Deck",
```

A screenshot of the altered zone locations:
![screenshot from 2015-09-10 11 51 25](https://cloud.githubusercontent.com/assets/1014341/9793719/eaf3bea6-57b4-11e5-8411-846a0cebf05f.png)

An image of the pre-altered zones with letter designations applied:
https://github.com/azavea/pwd-waterworks-revealed/issues/146#issuecomment-138637309

**Comment by mmcfarland** [comment]
@arobbi7 Are you interested in taking on this task?  If so, go ahead an assign it to yourself and I'll make sure it doesn't get included in the developer tasks for this coming sprint.

**Comment by arobbi7** [comment]
![slide1](https://cloud.githubusercontent.com/assets/12868342/9796149/9e898ede-57c2-11e5-8e4b-83ff73cd35ae.png)
