### ISSUE TITLE
 Design intro text treatment

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#148]
Request to have the intro text layout be "more welcoming (in terms of type treatment and hierarchy)".  I think this mostly means line spacing and font-size.

![screenshot from 2015-09-04 10 34 07](https://cloud.githubusercontent.com/assets/1014341/9686179/ab258318-52f0-11e5-82bc-8536dbcd74d9.png)

**Comment by lliss** [comment]
Take into account #151
