### ISSUE TITLE
Zone welcome dialog should not appear while aligning device with photo

### ISSUE THREAD

**Issue by arobbi7** [azavea/pwd-waterworks-revealed#153]
![img_3002](https://cloud.githubusercontent.com/assets/12868342/9737619/771f739e-5615-11e5-994d-9d1b965529b9.PNG)

**Comment by caseypt** [comment]
May be fixed by fixing https://github.com/azavea/pwd-waterworks-revealed/issues/142.

**Comment by lliss** [comment]
Yeah. I think this can be closed. I'll mark it as in review until we actually do a field test.

**Comment by caseypt** [comment]
I can reproduce it via the steps in #142, but I'm not sure if that's what happened here.

**Comment by arobbi7** [comment]
@caseypt After trying the steps in #142 I think that is what actually happened when I was walking around the site last weekend.

**Comment by caseypt** [comment]
@arobbi7 Cool! I just merged in the fix.
