### ISSUE TITLE
Update wiki page with new zone info

### ISSUE THREAD

**Issue by lliss** [azavea/pwd-waterworks-revealed#171]
We've added a zone (r3) and removed one (O). K has also been renamed. We should update the wiki page (https://github.com/azavea/pwd-waterworks-revealed/wiki) accordingly.

**Comment by arobbi7** [comment]
I edited the PDF with the official zone labels and updated the wiki page: https://github.com/azavea/pwd-waterworks-revealed/wiki

![2015_10_08_pwd_wwr_labeled_zones](https://cloud.githubusercontent.com/assets/12868342/10368731/c397919c-6da4-11e5-8337-8e1b309b6722.png)

**Comment by rajadain** [comment]
+1 confirmed that the Wiki page has RIII but no O.

**Comment by lliss** [comment]
+1 confirmed.
