### ISSUE TITLE
Provision four more Water Works testing devices

### ISSUE THREAD

**Issue by arobbi7** [azavea/pwd-waterworks-revealed#173]
UDIDs here: http://wiki.internal.azavea.com/doku.php?id=project:pwd_waterworks_revealed

**Comment by arobbi7** [comment]
I got the corrected UDID for the fourth device (property tag #66066) just now, and I've updated the wiki.

**Comment by lliss** [comment]
Awesome. Thanks.

**Comment by lliss** [comment]
I've confirmed added the new device IDs and updated the Jenkins build to use the new provisioning profile. Everything seems to be working on our iPads so I think this is safe to close. Can you confirm that you were able to properly install @arobbi7 ?

**Comment by arobbi7** [comment]
Looks great! +1
