### ISSUE TITLE
Add/Enable photo captions & attribution

### ISSUE THREAD

**Issue by ajrobbins** [azavea/pwd-waterworks-revealed#176]
At some point the photo captions and attribution information that were referenced in the original storyboards and content outline never made it into the app. It's possible that they are actually in the app, but are hidden at the moment. In either case, we need to add captions and attributions for the photos, as described in smb://fileshare.internal.azavea.com/projects/PWD_StormwaterBilling/documents/2016_03_29_WWR_storyboards.pdf and smb://fileshare.internal.azavea.com/projects/PWD_StormwaterBilling/documents/2016_03_29_WWR_picture-captions.pdf

**Comment by kellyi** [comment]
Got the captions to show, but they're currently obscured by a "Swipe left to continue" label across the bottom of the screen:

![screen shot 2016-03-30 at 3 08 28 pm](https://cloud.githubusercontent.com/assets/4165523/14154234/63e2e51c-f689-11e5-9587-f3a262b38412.png)

Looks like the app's currently concatenating the caption and the credit from a `zone.json` file:

https://github.com/azavea/pwd-waterworks-revealed/blob/master/src/quests/fairmount-water-works/l/zone.json
