### ISSUE TITLE
Zone reactivates after entering

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#59]
Occasionally, when in an active zone, it appears to reactivate and start the card series over again.

**Comment by mmcfarland** [comment]
@lliss @caseypt - we did not experience this in our field trial, right?  I think I had this in my previous test when we still had the expanding circle animation.  May be a non-issue.

**Comment by caseypt** [comment]
Correct. I do not recall seeing this.

**Comment by lliss** [comment]
I don't recall this either.

**Comment by caseypt** [comment]
Closing. Superseded by #99 and #108
