### ISSUE TITLE
Make ghost trail more intense

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#61]
When actually using the GPS provided coordinates, the ghost trail dots clump a little more and it's hard to distinguish your current location, especially if walking circuitously.  However, it's a nice feature to help orient the direction you're walking in.  I think we should just ramp down the opacity harder for the ghosts.

**Comment by caseypt** [comment]
Consolidated in #94

**Comment by caseypt** [comment]
Consolidated in #94
