### ISSUE TITLE
Find replacement for grunt-phonegap-build

### ISSUE THREAD

**Issue by caseypt** [azavea/pwd-waterworks-revealed#71]
I think our app file is too big for this library, as it fails to upload the file and errors out. See this build for an example: http://jenkins01.internal.azavea.com/job/PWD_Water_Revealed/96/console

The library is no longer maintained: https://github.com/centralway/grunt-phonegap-build
https://github.com/centralway/grunt-phonegap-build/issues/12#issuecomment-65380642 (He is not maintaining the fork either)

**Comment by lliss** [comment]
No longer using hosted phonegap build.
