### ISSUE TITLE
Improve location usage message.

### ISSUE THREAD

**Issue by lliss** [azavea/pwd-waterworks-revealed#76]
When starting the application a user is prompted that the application would like to use location information. The message has a long string that references the index.html page. We should try to change this to something better looking.

**Comment by caseypt** [comment]
Potential solution here: http://stackoverflow.com/questions/1673579/location-permission-alert-on-iphone-with-phonegap/5018461#5018461

**Comment by lliss** [comment]
Strangely this hasn't been happening with my new builds.

**Comment by lliss** [comment]
Marking this as invalid for now since I cannot reproduce it.

**Comment by caseypt** [comment]
I could not reproduce this either.

**Comment by caseypt** [comment]
Point given to #103
