### ISSUE TITLE
Reorient map while walking

### ISSUE THREAD

**Issue by lliss** [azavea/pwd-waterworks-revealed#79]
Since the map is set to have north at the top of the screen no matter what, it is sometime hard to tell which way you are moving with respect to reality when you are walking and looking at the tablet. It might be good to have the map reorient to the current direction.

**Comment by gagan-bansal** [comment]
It may interest to you http://maps-on-blackboard.com/articles/rotate-and-pinch-osm-map-with-geojson-data/ 
This is based on [emptymap.js](http://maps-on-blackboard.com/articles/rotate-and-pinch-osm-map-with-geojson-data/) and [Hammer.js](http://hammerjs.github.io/)
