### ISSUE TITLE
Target circle sizes

### ISSUE THREAD

**Issue by lliss** [azavea/pwd-waterworks-revealed#84]
The zone circles are very large and close together, it makes it easy to accidentally wander to the wrong zone or to leave a zone or enter one by skirting the edge. Consider reducing the size. This will depend on the reliable location accuracy we can get from the devices.

**Comment by caseypt** [comment]
Share a point with #59

**Comment by mmcfarland** [comment]
Client confirmed that the circle sizes are good, but the placement of them needs to be tweaked.  Will add a new card for that.
