### ISSUE TITLE
Enable quest confirmation

### ISSUE THREAD

**Issue by jfrankl** [azavea/pwd-waterworks-revealed#92]
Currently, when a user walks into a quest area, the quest immediately fades in and takes over the application. I think it would be helpful to add an intermediary step that notifies the user when they have entered a quest area and allow them to decide to explore it.

69e50e671d6a9081ed4db6e3c0c6f03dbd88e723 adds in the html and css building blocks for this notification. I need a developer to make it function. 

- ```#confirmation``` should appear when a user enters the quest area by adding class ```.active```.
- ```#confirmation-quest-name``` should be replaced with the quest name
- clicking on the "explore" button should fade in the overlay

![image](https://cloud.githubusercontent.com/assets/1809908/8216919/b1ba2b24-1507-11e5-9f93-2f7e89186d3f.png)

![image](https://cloud.githubusercontent.com/assets/1809908/8216922/beac0712-1507-11e5-82f7-c1c5887dced2.png)

![image](https://cloud.githubusercontent.com/assets/1809908/8216941/e93f5d12-1507-11e5-81bb-4acc1c4f9f26.png)

![image](https://cloud.githubusercontent.com/assets/1809908/8216954/01798f74-1508-11e5-87c7-70727bb433bb.png)

**Comment by mmcfarland** [comment]
Just to be clear, this confirmation does not happen in the first primary item, right - the caption space for that photo is still Good To Go?

**Comment by caseypt** [comment]
Right. This happens before the slideshow is launched.

**Comment by caseypt** [comment]
Closing for now.
