### ISSUE TITLE
Enable quest exit notification

### ISSUE THREAD

**Issue by mmcfarland** [azavea/pwd-waterworks-revealed#99]
During some field testing, I noticed what I initially thought was a recurrence of #59, but was actually that the series of photos ends and goes back to the map, but I just didn't realize (This may have been the original cause of #59 anyway).  Since each zone has a variable number of quests, the photos seem to end unexpectedly and a little unceremoniously.  If we had a "last page" or some other indication that the series was over, I think it'd reduce the confusion.

**Comment by caseypt** [comment]
Discussed with @jfrankl. This screen should not be swipeable, and should instead have a button ("Finish Quest" or something similar) that, when tapped, exits the slideshow.
